version: "3.7"
services:
  db:
    image: mysql:5.7
    container_name: PetVerse-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: d4t4!P3t
      MYSQL_DATABASE: PetVerse
      MYSQL_USER: PVadmin
      MYSQL_PASSWORD: P3!Verse
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: PetVerse-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: d4t4!P3t
    ports:
      - "8000:80"

volumes:
  db_data:
